# Julia cheatsheet

Overall, Julia's syntax is very similar to that of Python, and, in a way, to that of MATLAB.  Sometimes, however, there are small differences that might be annoying to the newcomer. Let's have a look at some of them.

#### Applying functions to arrays

Python and MATLAB are generally very forgiving when you define a function, and try to apply it to an array of numbers. They have their ways of figuring out whether you want to apply the function elementwise, or not. Due to Julia's design principles, however, its compiler is a little more strict, and sometimes you need to be more specific about the type of argument a function can expect.

Say we define the following simple function:

In [1]:
f(x) = x^2

f (generic function with 1 method)

We haven't said anything about the type of `x`, but we're using the squaring operator. You can check for which data types that operator is defined by typing `methods(^)`. If you do that you'll see it's defined for a large set of type combinations, but the array is not one of them! So if we try to do the following we get an error:

In [2]:
f([1, 2, 3])

MethodError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Float16, ::Integer) at math.jl:795
  ^(!Matched::Missing, ::Integer) at missing.jl:124
  ^(!Matched::Missing, ::Number) at missing.jl:97
  ...

Inspecting the error message we see that the power operator `^` is not defined for 1D arrays. We can solve this by explicitly broadcasting using dot notation:

In [3]:
f.([1 2 3])

1×3 Array{Int64,2}:
 1  4  9

This applies the function to an array element-wise.

If you get an unexpected error message it can be worthwhile to check and make sure the function you're using is defined for the datatype you're trying to feed into it. Sometimes it's obvious to you what you want, but not to the compiler! If you have an array of complex numbers, for instance, and want to know their absolute values, you need dot notation:

In [4]:
abs.([1 + im, 3 + im, 5 + im])

3-element Array{Float64,1}:
 1.4142135623730951
 3.1622776601683795
 5.099019513592785 

#### Array construction
Much like MATLAB, Julia allows for array construction using spaces, commas, and semicolons. Spaces and semicolons can be thought of as horizontal and vertical concatenation, respectively, whereas commas simply combine objects into arrays of objects without necessarily concatenating them. (If these objects happen to be numbers the result is a normal array, of course.) This produces the following behavior:

In [5]:
[6, 8, 3, 5]

4-element Array{Int64,1}:
 6
 8
 3
 5

In [6]:
[6 8; 3 5]

2×2 Array{Int64,2}:
 6  8
 3  5

In [7]:
[[6, 8] [3, 5]]

2×2 Array{Int64,2}:
 6  3
 8  5

In [8]:
[[6, 8]; [3, 5]]

4-element Array{Int64,1}:
 6
 8
 3
 5

#### Generating ranges

We often need to construct an array of evenly spaced numbers (think of MATLAB's `linspace()` or `range()`, or Python's/NumPy's equivalent `np.linspace()` and `np.arange()`). Both functionalities are captured by Julia's `range()`, which takes a named argument to determine whether it's linspace-like or range-like:

In [9]:
range(0, 10, length = 23)       # linspace-like

0.0:0.45454545454545453:10.0

In [10]:
range(0, 10, step = 0.1)        # range-like

0.0:0.1:10.0

But what are these things that are returned?

This is a `StepRangeLen` object (you can check this using the `typeof()` macro). Sometimes, it may be necessary to expand it, you can them simply use a semicolon to expand it (concatenating all elements vertically, as it were):

In [11]:
[0:0.2:1;]

6-element Array{Float64,1}:
 0.0
 0.2
 0.4
 0.6
 0.8
 1.0

#### Finally, some miscellaneous useful functions

`typeof()` allows us to check the type of a variable:

In [12]:
a = 6835
typeof(a)

Int64

`isa(a, Type)` checks whether a is of the type we specify (this is equivalent to `typeof(a) <: Type`):

In [13]:
a = 6.835
isa(a, Float64)

true

`fieldnames()` returns all fields of a certain datatype, which can be accessed using dot notation:

In [20]:
a = 0:0.1:10
fieldnames( typeof(a) )

(:ref, :step, :len, :offset)

`@time` is a macro that can be inserted in front of any line, it will provide instant timing info:

In [25]:
@time f.( 0:0.000001:10 );

  0.325992 seconds (10 allocations: 76.294 MiB, 73.16% gc time)
